# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skillTip.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class skillInfo(QtWidgets.QWidget):
    def __init__(self, json=None, parent=None):
        super().__init__(parent)
        self.json = json
        self.setupUi()

    def setupUi(self):
        self.setWindowFlags(
            QtCore.Qt.CustomizeWindowHint |
            QtCore.Qt.FramelessWindowHint |
            QtCore.Qt.ToolTip
        )

        self.setObjectName("Skill")
        self.resize(259, 349)
        self.setStyleSheet("background-color: rgb(79, 79, 79);")

        self.skillName = QtWidgets.QLabel(self)
        self.skillName.setGeometry(QtCore.QRect(0, 10, 301, 21))
        self.skillName.setStyleSheet("color: rgb(255, 0, 255); font-size: 16px; padding-left: 7px;")
        self.skillName.setObjectName("skillName")
        self.skillImg = QtWidgets.QLabel(self)
        self.skillImg.setGeometry(QtCore.QRect(20, 40, 64, 64))
        self.skillImg.setText("")
        self.skillImg.setPixmap(QtGui.QPixmap("qt-creator-files/dummy-item.png"))
        self.skillImg.setObjectName("skillImg")
        self.attributes = QtWidgets.QListWidget(self)
        self.attributes.setGeometry(QtCore.QRect(100, 40, 81, 301))
        self.attributes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.attributes.setStyleSheet("color: rgb(227, 227, 227); font-size: 14px;")
        self.attributes.setFlow(QtWidgets.QListView.TopToBottom)
        self.attributes.setProperty("isWrapping", False)
        self.attributes.setResizeMode(QtWidgets.QListView.Fixed)
        self.attributes.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.attributes.setItemAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignJustify|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.attributes.setObjectName("attributes")

        self.totalList = QtWidgets.QListWidget(self)
        self.totalList.setGeometry(QtCore.QRect(180, 40, 71, 301))
        self.totalList.setStyleSheet("color: rgb(0, 231, 231); font-size: 14px;")
        self.totalList.setObjectName("totalList")

        # for i in range(0, len(self.json.get("stats")[0])):
        #     item = QtWidgets.QListWidgetItem()
        #     item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        #     self.attributes.add(item)

        for key in self.json.get("stats")[0]:
            item = QtWidgets.QListWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
            item.setText(key)
            self.attributes.addItem(item)
            val = QtWidgets.QListWidgetItem()
            val.setText(str(self.json.get("stats")[0].get(key)))
            self.totalList.addItem(val)

        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.attributes.addItem(item)
        
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.totalList.addItem(item)

        # self.retranslateUi(Form)
        # QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.skillName.setText(_translate("Form", "Dummy Skill"))
        __sortingEnabled = self.attributes.isSortingEnabled()
        self.attributes.setSortingEnabled(False)
        item = self.attributes.item(0)
        item.setText(_translate("Form", "STR:"))
        item = self.attributes.item(1)
        item.setText(_translate("Form", "DEX:"))
        item = self.attributes.item(2)
        item.setText(_translate("Form", "INT:"))
        item = self.attributes.item(3)
        item.setText(_translate("Form", "LUK:"))
        item = self.attributes.item(4)
        item.setText(_translate("Form", "HP:"))
        item = self.attributes.item(5)
        item.setText(_translate("Form", "MP:"))
        item = self.attributes.item(6)
        item.setText(_translate("Form", "ATK:"))
        item = self.attributes.item(7)
        item.setText(_translate("Form", "M.ATK:"))
        item = self.attributes.item(8)
        item.setText(_translate("Form", "DEF:"))
        item = self.attributes.item(9)
        item.setText(_translate("Form", "SPEED:"))
        item = self.attributes.item(10)
        item.setText(_translate("Form", "JUMP:"))
        item = self.attributes.item(11)
        item.setText(_translate("Form", "BOSS:"))
        item = self.attributes.item(12)
        item.setText(_translate("Form", "CRITRATE:"))
        item = self.attributes.item(13)
        item.setText(_translate("Form", "ALL%:"))
        self.attributes.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.totalList.isSortingEnabled()
        self.totalList.setSortingEnabled(False)
        item = self.totalList.item(0)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(1)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(2)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(3)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(4)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(5)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(6)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(7)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(8)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(9)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(10)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(11)
        item.setText(_translate("Form", "+555"))
        item = self.totalList.item(12)
        item.setText(_translate("Form", "+555"))
        self.totalList.setSortingEnabled(__sortingEnabled)
