# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verify.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class verify_equip(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi()

    #text = stat text name
    #yCord = y coordinate of EditLine boxes
    def createStatEntry(self, text, yCord):
        label = QtWidgets.QLabel(self)
        base = QtWidgets.QLineEdit(self)
        flame = QtWidgets.QLineEdit(self)
        star = QtWidgets.QLineEdit(self)
        button = QtWidgets.QPushButton(self)
        font = QtGui.QFont()
        font.setPointSize(11)
        label.setGeometry(QtCore.QRect(270, yCord + 4, 61, 16))
        label.setFont(font)
        label.setTextFormat(QtCore.Qt.AutoText)
        label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        label.setText(text)
        lowerText = text.lower()
        base.setGeometry(QtCore.QRect(340, yCord, 41, 20))
        base.setObjectName(lowerText + "BaseEdit")
        base.setPlaceholderText("0")
        flame.setGeometry(QtCore.QRect(450, yCord, 41, 20))
        flame.setObjectName(lowerText + "FlameEdit")
        flame.setPlaceholderText("0")
        star.setGeometry(QtCore.QRect(570, yCord, 41, 20))
        star.setObjectName(lowerText + "StarEdit")
        star.setPlaceholderText("0")
        button.setGeometry(QtCore.QRect(510, yCord - 1, 41, 23))

    def populateMainPotentialCombo(self, combo):
        combo.addItem("NONE")
        combo.addItem("STR%")
        combo.addItem("DEX%")
        combo.addItem("INT%")
        combo.addItem("LUK%")
        combo.addItem("ALL%")
        combo.addItem("HP%")
        combo.addItem("ATT%")
        combo.addItem("M.ATT%")
        combo.addItem("DEF%")
        combo.addItem("DAMAGE%")
        combo.addItem("BOSS%")
        combo.addItem("CRIT. DMG%")
        combo.addItem("IGNORE%")
        combo.addItem("STR")
        combo.addItem("DEX")
        combo.addItem("INT")
        combo.addItem("LUK")
        combo.addItem("ALL")
        combo.addItem("HP")
        combo.addItem("ATT")
        combo.addItem("M.ATT")
        combo.addItem("DEF")
        combo.addItem("ATT +? / 10 LEVELS")
        combo.addItem("M.ATT +? / 10 LEVELS")

    def populateBonusPotentailCombo(self, combo):
        self.populateMainPotentialCombo(combo)
        combo.addItem("STR +? / 10 LEVELS")
        combo.addItem("DEX +? / 10 LEVELS")
        combo.addItem("INT +? / 10 LEVELS")
        combo.addItem("LUK +? / 10 LEVELS")

    def setupUi(self):
        self.setObjectName("Verify Item")
        self.resize(621, 745)
        self.setMinimumSize(621, 745)
        self.itemWindow = QtWidgets.QLabel(self)
        self.itemWindow.setGeometry(QtCore.QRect(10, 10, 261, 681))
        self.itemWindow.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.itemWindow.setObjectName("itemWindow")

        font = QtGui.QFont()
        font.setPointSize(11)

        self.nameEdit = QtWidgets.QLineEdit(self)
        self.nameEdit.setGeometry(QtCore.QRect(340, 6, 271, 20))
        self.nameEdit.setObjectName("nameEdit")

        self.nameLabel = QtWidgets.QLabel(self)
        self.nameLabel.setGeometry(QtCore.QRect(270, 10, 61, 16))
        
        self.nameLabel.setFont(font)
        self.nameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.nameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLabel.setText("Name")

        self.typeLabel = QtWidgets.QLabel(self)
        self.typeLabel.setGeometry(QtCore.QRect(270, 40, 61, 16))
        self.typeLabel.setFont(font)
        self.typeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.typeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.typeLabel.setObjectName("typeLabel")
        self.typeLabel.setText("Type")

        self.typeCombo = QtWidgets.QComboBox(self)
        self.typeCombo.setGeometry(QtCore.QRect(340, 34, 101, 22))
        self.typeCombo.setObjectName("typeCombo")
        self.typeCombo.addItem("Weapon")
        self.typeCombo.addItem("Secondary")
        self.typeCombo.addItem("Emblem")
        self.typeCombo.addItem("Hat")
        self.typeCombo.addItem("Top")
        self.typeCombo.addItem("Overall")
        self.typeCombo.addItem("Bottom")
        self.typeCombo.addItem("Glove")
        self.typeCombo.addItem("Shoe")
        self.typeCombo.addItem("Cape")
        self.typeCombo.addItem("Face")
        self.typeCombo.addItem("Eye")
        self.typeCombo.addItem("Belt")
        self.typeCombo.addItem("Ring")
        self.typeCombo.addItem("Pendant")
        self.typeCombo.addItem("Shoulder")
        self.typeCombo.addItem("Earring")
        self.typeCombo.addItem("Heart")
        self.typeCombo.addItem("Badge")
        self.typeCombo.addItem("Medal")
        self.typeCombo.addItem("Pocket")

        self.subtypeLabel = QtWidgets.QLabel(self)
        self.subtypeLabel.setGeometry(QtCore.QRect(440, 40, 61, 16))
        self.subtypeLabel.setFont(font)
        self.subtypeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.subtypeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.subtypeLabel.setObjectName("subtypeLabel")
        

        self.subtypeCombo = QtWidgets.QComboBox(self)
        self.subtypeCombo.setEnabled(False)
        self.subtypeCombo.setGeometry(QtCore.QRect(510, 34, 101, 22))
        self.subtypeCombo.setObjectName("subtypeCombo")
        self.subtypeCombo.addItem("Non-shield")
        self.subtypeCombo.addItem("Shield")

        self.setLabel = QtWidgets.QLabel(self)
        self.setLabel.setGeometry(QtCore.QRect(440, 70, 61, 16))
        self.setLabel.setFont(font)
        self.setLabel.setTextFormat(QtCore.Qt.AutoText)
        self.setLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.setLabel.setObjectName("setLabel")
        self.setCombo = QtWidgets.QComboBox(self)
        self.setCombo.setGeometry(QtCore.QRect(510, 64, 101, 22))
        self.setCombo.setObjectName("setCombo")
        self.setCombo.addItem("None")
        self.setCombo.addItem("Arcane")
        self.setCombo.addItem("Chaos Root Abyss")
        self.setCombo.addItem("Absolabs")
        self.setCombo.addItem("Boss")
        self.setCombo.addItem("Hard Boss")
        self.setCombo.addItem("Meister")
        self.setCombo.addItem("Gollux")

        self.starsLabel = QtWidgets.QLabel(self)
        self.starsLabel.setGeometry(QtCore.QRect(270, 70, 61, 16))
        self.starsLabel.setFont(font)
        self.starsLabel.setTextFormat(QtCore.Qt.AutoText)
        self.starsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.starsLabel.setObjectName("starsLabel")
        self.starsLabel.setText("Stars")

        self.starSpinbox = QtWidgets.QSpinBox(self)
        self.starSpinbox.setGeometry(QtCore.QRect(340, 64, 42, 22))
        self.starSpinbox.setMaximum(25)
        self.starSpinbox.setValue(0)
        self.starSpinbox.setObjectName("starSpinbox")

        self.baseLabel = QtWidgets.QLabel(self)
        self.baseLabel.setGeometry(QtCore.QRect(300, 95, 311, 16))
        self.baseLabel.setFont(font)
        self.baseLabel.setTextFormat(QtCore.Qt.AutoText)
        self.baseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.baseLabel.setObjectName("baseLabel")
        self.baseLabel.setText("---BASE STATS (BASE/FLAME/STAR)---")

        self.createStatEntry("STR", 120)
        self.createStatEntry("DEX", 150)
        self.createStatEntry("INT", 180)
        self.createStatEntry("LUK", 210)
        self.createStatEntry("ATK", 240)
        self.createStatEntry("MATK", 270)
        self.createStatEntry("HP", 300)
        self.createStatEntry("DEF", 330)
        self.createStatEntry("IGNORE", 360)
        self.createStatEntry("BOSS", 390)
        self.createStatEntry("DAMAGE", 420)
        self.createStatEntry("ALL", 450)

        self.mainLabel = QtWidgets.QLabel(self)
        self.mainLabel.setGeometry(QtCore.QRect(300, 480, 311, 16))
        self.mainLabel.setFont(font)
        self.mainLabel.setTextFormat(QtCore.Qt.AutoText)
        self.mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.mainLabel.setText("---MAIN POTENTIAL---")
        
        
        self.mainEdit1 = QtWidgets.QLineEdit(self)
        self.mainEdit1.setGeometry(QtCore.QRect(540, 500, 41, 20))
        self.mainEdit1.setText("")
        self.mainEdit1.setObjectName("mainEdit1")
        self.mainEdit2 = QtWidgets.QLineEdit(self)
        self.mainEdit2.setGeometry(QtCore.QRect(540, 530, 41, 20))
        self.mainEdit2.setText("")
        self.mainEdit2.setObjectName("mainEdit2")
        self.mainEdit3 = QtWidgets.QLineEdit(self)
        self.mainEdit3.setGeometry(QtCore.QRect(540, 560, 41, 20))
        self.mainEdit3.setText("")
        self.mainEdit3.setObjectName("mainEdit3")
        self.mainCombo1 = QtWidgets.QComboBox(self)
        self.mainCombo1.setGeometry(QtCore.QRect(330, 500, 191, 22))
        self.mainCombo1.setObjectName("mainCombo1")
        self.mainCombo2 = QtWidgets.QComboBox(self)
        self.mainCombo2.setGeometry(QtCore.QRect(330, 530, 191, 22))
        self.mainCombo2.setObjectName("mainCombo2")
        self.mainCombo3 = QtWidgets.QComboBox(self)
        self.mainCombo3.setGeometry(QtCore.QRect(330, 560, 191, 22))
        self.mainCombo3.setObjectName("mainCombo3")

        self.populateMainPotentialCombo(self.mainCombo1)
        self.populateMainPotentialCombo(self.mainCombo2)
        self.populateMainPotentialCombo(self.mainCombo3)

        self.bonusCombo1 = QtWidgets.QComboBox(self)
        self.bonusCombo1.setGeometry(QtCore.QRect(330, 610, 191, 22))
        self.bonusCombo1.setObjectName("bonusCombo1")
        self.bonusCombo2 = QtWidgets.QComboBox(self)
        self.bonusCombo2.setGeometry(QtCore.QRect(330, 640, 191, 22))
        self.bonusCombo2.setObjectName("bonusCombo2")
        self.bonusCombo3 = QtWidgets.QComboBox(self)
        self.bonusCombo3.setGeometry(QtCore.QRect(330, 670, 191, 22))
        self.bonusCombo3.setObjectName("bonusCombo3")

        self.populateBonusPotentailCombo(self.bonusCombo1)
        self.populateBonusPotentailCombo(self.bonusCombo2)
        self.populateBonusPotentailCombo(self.bonusCombo3)

        self.bonusLabel = QtWidgets.QLabel(self)
        self.bonusLabel.setGeometry(QtCore.QRect(300, 590, 311, 16))
        self.bonusLabel.setFont(font)
        self.bonusLabel.setTextFormat(QtCore.Qt.AutoText)
        self.bonusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bonusLabel.setObjectName("bonusLabel")
        self.bonusLabel.setText("---BONUS POTENTIAL---")
        self.bonusEdit1 = QtWidgets.QLineEdit(self)
        self.bonusEdit1.setGeometry(QtCore.QRect(540, 610, 41, 20))
        self.bonusEdit1.setText("")
        self.bonusEdit1.setObjectName("bonusEdit1")
        self.bonusEdit3 = QtWidgets.QLineEdit(self)
        self.bonusEdit3.setGeometry(QtCore.QRect(540, 670, 41, 20))
        self.bonusEdit3.setText("")
        self.bonusEdit3.setObjectName("bonusEdit3")
        self.bonusEdit2 = QtWidgets.QLineEdit(self)
        self.bonusEdit2.setGeometry(QtCore.QRect(540, 640, 41, 20))
        self.bonusEdit2.setText("")
        self.bonusEdit2.setObjectName("bonusEdit2")
        self.confirmButton = QtWidgets.QPushButton(self)
        self.confirmButton.setGeometry(QtCore.QRect(330, 702, 171, 31))
        self.confirmButton.setObjectName("confirmButton")
        self.confirmButton.setText("Confirm Item")
        self.discardButton = QtWidgets.QPushButton(self)
        self.discardButton.setGeometry(QtCore.QRect(510, 710, 75, 23))
        self.discardButton.setObjectName("discardButton")
        self.discardButton.setText("Discard Item")
